# Generated by Django 4.0.2 on 2022-02-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0003_topic_title_alter_topic_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('folder', 'name')},
        ),
    ]
